# print(int(3.14))
# # print(int(10+5j))
# print(int(True))
# print(int(False))
# # print(int("4.22"))
# print(int("4"))

# print(float(3))
# # print(float(50+2j))
# print(float(True))
# print(float(False))
# print(float("3.14"))
# print(float("3"))

# print(complex(3))
# print(complex(3.14))
# print(complex(True))
# print(complex(False))
# print(complex("5"))
# print(complex("5.6"))
# print(complex("name"))
# print(complex(5,-3))
# print(complex(True, False))


# print(bool(0))
# print(bool(15))
# print(bool(3.14))
# print(bool(0.0))
# print(bool(1+2j))
# print(bool(0+0j))
# print(bool(-1))
# print(bool(False))
# print(bool(True))
# print(bool(""))
# print(bool("Suraj"))